app:
  name: Restaurant API sever
  port: 8001
typeorm:
  name: default
  type: mysql
  port: 3306
  username: restaurant_api_local_user
  password: sQa%UNffrRxsbOVc
  database: restaurant_api_local
  synchronize: true
