---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api-server
  labels:
    app: restaurant-api-server
spec:
  selector:
    matchLabels:
      app: restaurant-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: restaurant-api-server
    spec:
      containers:
      - name: restaurant-api-server
        image: gcr.io/baemin-clone-coding/restaurant-api-server:0.0.1
        ports:
          - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 3
          periodSeconds: 15

